### PR TITLE
I am interested in using your game on my website. Could you add a license file like the MIT one in this pull request so I know how you want your software used?

### PR DESCRIPTION
**Pull request by jpbida**

### CODE REVIEW

**Comment by mgottschlag** [comment]
I've added two license headers to the two files which were missing them (unit tests). I don't think the information should be deduplicated in a separate license file, as I'd imagine this code to be used in a copy/paste fashion quite often.

But seriously: Did you have to waste my and everybody elses time by sending these hundreds of pull requests without even looking at the code? It's a pretty obvious lie that you want to use this game on your website. I guess the real motivation rather is to reduce the amount of code out there without a license - a honorable goal, but if you automate that, then:
a) Please automate it properly (I assume that it was in some way automated, because your pull request says "game", yet it is easily visible that this isn't a game) and make your code scan for license headers in source code files.
b) Only do it when it is actually of interest to the public. In this case, I think you are the first to ask me about this code. Nobody else has used it yet (and, given that it is already in that state for 6 years, I don't think anybody ever will), and I think the same applies for quite some of the other 700 repositories you sent pull requests to. You don't achieve anything sending these pull requests, compared to just asking when you use the code for the first time. If people respond now, they'd also respond at that later point in time when someone is *actually* interested in the code.

**Comment by mgottschlag** [comment]
Oh, and while we're at it: Please fix the indentation of that license file. I wouldn't want my license to be deeply indented for no particular reason, and I wouldn't want those trailing spaces in the empty lines either.

**Comment by ifvictr** [comment]
Looks like your repository's name contained the word "math". ;)

**Comment by jpbida** [comment]
Sorry, I did end up making a short list of games we played as a group.  Wish github would just require people to actively select a license for public repos. Even if a choice was "Not for public use", it would help me to know it was an active choice.

**Pull request closed without merging**
